import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { recordTrainingAttendance, respondToNomination, setNominationStream } from "@/app/timy/[teamId]/nominacie/actions";

type Row = { nomination_id: string; team_id: string; team_name: string; title: string; event_type: string; starts_at: string; ends_at: string | null; location: string | null; note: string | null; nomination_status: string; player_id: string; player_name: string; is_nominated: boolean; response: "pending" | "accepted" | "declined" | null; responded_at: string | null; can_respond: boolean; decline_reason: string | null; attendance_status: "present" | "absent" | null; attendance_recorded_at: string | null; can_manage: boolean };
type StreamInfo = { stream_url: string | null; stream_status: "scheduled" | "live" | "ended" | null; can_manage: boolean };
const eventNames: Record<string, string> = { match: "Zápas", tournament: "Turnaj", training: "Tréning", other: "Iná udalosť" };
const responseNames = { pending: "Čaká na odpoveď", accepted: "Zúčastní sa", declined: "Nezúčastní sa" };
const responseClass = { pending: "bg-amber-50 text-amber-800", accepted: "bg-emerald-50 text-emerald-700", declined: "bg-red-50 text-red-700" };
const attendanceNames = { present: "Bol na tréningu", absent: "Chýbal", unmarked: "Nezaznamenané" };
const attendanceClass = { present: "bg-emerald-100 text-emerald-800", absent: "bg-red-100 text-red-800", unmarked: "bg-slate-100 text-slate-600" };
const dateTime = new Intl.DateTimeFormat("sk-SK", { dateStyle: "long", timeStyle: "short", timeZone: "Europe/Bratislava" });
const streamNames = { scheduled: "Prenos je pripravený", live: "Práve naživo", ended: "Prenos bol ukončený" } as const;

export default async function NominationPage({ params, searchParams }: { params: Promise<{ nominationId: string }>; searchParams: Promise<{ stav?: string }> }) {
  const { nominationId } = await params;
  const query = await searchParams;
  if (!/^[0-9a-f-]{36}$/i.test(nominationId)) notFound();
  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getClaims();
  if (!auth?.claims?.sub) redirect("/prihlasenie");
  const [{ data, error }, { data: streamData, error: streamError }] = await Promise.all([
    supabase.rpc("get_nomination_roster_v3", { p_nomination_id: nominationId }),
    supabase.rpc("get_team_nomination_stream", { p_nomination_id: nominationId }),
  ]);
  if (error || streamError) redirect("/ucet");
  const rows = (data as Row[] | null) ?? [];
  if (rows.length === 0) notFound();
  const event = rows[0];
  const stream = ((streamData as StreamInfo[] | null) ?? [])[0];
  const nominated = rows.filter((row) => row.is_nominated);
  const counts = nominated.reduce((all, row) => row.response ? ({ ...all, [row.response]: all[row.response] + 1 }) : all, { pending: 0, accepted: 0, declined: 0 });
  const attendanceCounts = nominated.reduce((all, row) => {
    const status = row.attendance_status ?? "unmarked";
    return { ...all, [status]: all[status] + 1 };
  }, { present: 0, absent: 0, unmarked: 0 });

  return <section className="mx-auto max-w-4xl px-5 py-12 sm:py-16"><Link className="text-sm font-bold text-arena-700" href={`/timy/${event.team_id}/nominacie`}>← Všetky nominácie</Link>
    {query.stav === "vytvorena" && <p className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 font-bold text-emerald-800">Nominácia bola vytvorená a je viditeľná pre celý tím.</p>}{query.stav === "odpoved-ulozena" && <p className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 font-bold text-emerald-800">Odpoveď bola uložená.</p>}{query.stav === "dochadzka-ulozena" && <p className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 font-bold text-emerald-800">Dochádzka bola uložená.</p>}{query.stav === "prenos-ulozeny" && <p className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 font-bold text-emerald-800">Odkaz na prenos bol uložený.</p>}{query.stav === "prenos-odstraneny" && <p className="mt-5 rounded-2xl border border-slate-200 bg-white px-5 py-4 font-bold text-slate-700">Odkaz na prenos bol odstránený.</p>}
    <header className="mt-5 rounded-3xl bg-ink p-6 text-white sm:p-8"><p className="text-xs font-extrabold uppercase tracking-widest text-arena-300">{eventNames[event.event_type] ?? "Udalosť"} · {event.team_name}</p><h1 className="mt-2 text-3xl font-extrabold">{event.title}</h1><p className="mt-3 text-slate-200">{dateTime.format(new Date(event.starts_at))}{event.ends_at ? ` – ${new Intl.DateTimeFormat("sk-SK", { timeStyle: "short", timeZone: "Europe/Bratislava" }).format(new Date(event.ends_at))}` : ""}{event.location ? ` · ${event.location}` : ""}</p>{event.note && <p className="mt-5 rounded-2xl bg-white/10 p-4 text-sm leading-6 text-slate-100">{event.note}</p>}<div className="mt-5 flex flex-wrap gap-2 text-sm font-bold"><span className="rounded-full bg-blue-400/20 px-3 py-1 text-blue-100">Nominovaní: {nominated.length}</span><span className="rounded-full bg-white/10 px-3 py-1 text-slate-200">Nenominovaní: {rows.length - nominated.length}</span><span className="rounded-full bg-emerald-400/20 px-3 py-1 text-emerald-200">Potvrdení: {counts.accepted}</span><span className="rounded-full bg-red-400/20 px-3 py-1 text-red-200">Neprídu: {counts.declined}</span><span className="rounded-full bg-amber-300/20 px-3 py-1 text-amber-100">Čaká: {counts.pending}</span></div>{event.event_type === "training" && <div className="mt-3 flex flex-wrap gap-2 text-sm font-bold"><span className="rounded-full bg-white/10 px-3 py-1 text-emerald-200">Dochádzka: {attendanceCounts.present} prítomní</span><span className="rounded-full bg-white/10 px-3 py-1 text-red-200">{attendanceCounts.absent} neprítomní</span><span className="rounded-full bg-white/10 px-3 py-1 text-slate-200">{attendanceCounts.unmarked} nezadané</span></div>}</header>
    {(event.event_type === "match" || event.event_type === "tournament") && stream?.stream_url && <div className={`mt-5 rounded-3xl border p-5 sm:flex sm:items-center sm:justify-between sm:gap-6 ${stream.stream_status === "live" ? "border-red-200 bg-red-50" : "border-blue-200 bg-blue-50"}`}><div><p className={`text-xs font-extrabold uppercase tracking-wider ${stream.stream_status === "live" ? "text-red-700" : "text-blue-700"}`}>{stream.stream_status === "live" && <span className="mr-2 inline-block h-2.5 w-2.5 animate-pulse rounded-full bg-red-600"/>}{stream.stream_status ? streamNames[stream.stream_status] : "Živý prenos"}</p><h2 className="mt-2 text-xl font-extrabold text-ink">{stream.stream_status === "ended" ? "Pozrite si záznam udalosti" : "Sledujte udalosť online"}</h2></div><a className="btn-primary mt-4 justify-center sm:mt-0" href={stream.stream_url} rel="noopener noreferrer" target="_blank">{stream.stream_status === "ended" ? "Otvoriť záznam ↗" : "Otvoriť živý prenos ↗"}</a></div>}
    {(event.event_type === "match" || event.event_type === "tournament") && stream?.can_manage && <details className="mt-5 rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-extrabold text-arena-700">{stream.stream_url ? "Upraviť živý prenos" : "Pridať živý prenos"}</summary><p className="mt-2 text-sm text-slate-600">Vložte bezpečný odkaz z YouTube, Facebooku alebo inej streamovacej služby.</p><form action={setNominationStream} className="mt-4 grid gap-3 sm:grid-cols-[1fr_11rem_auto]"><input name="nominationId" type="hidden" value={nominationId}/><input name="teamId" type="hidden" value={event.team_id}/><label><span className="label">Odkaz na prenos</span><input className="field" defaultValue={stream.stream_url ?? ""} maxLength={500} name="streamUrl" placeholder="https://..." required type="url"/></label><label><span className="label">Stav</span><select className="field" defaultValue={stream.stream_status ?? "scheduled"} name="streamStatus"><option value="scheduled">Pripravený</option><option value="live">Naživo</option><option value="ended">Ukončený</option></select></label><button className="btn-primary self-end justify-center" type="submit">Uložiť prenos</button></form>{stream.stream_url && <form action={setNominationStream} className="mt-3"><input name="nominationId" type="hidden" value={nominationId}/><input name="teamId" type="hidden" value={event.team_id}/><input name="remove" type="hidden" value="true"/><button className="text-sm font-bold text-red-700" type="submit">Odstrániť odkaz na prenos</button></form>}</details>}
    {(event.event_type === "match" || event.event_type === "tournament") && <p className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 px-5 py-4 text-sm font-semibold text-blue-900">Nomináciu vidí celý tím. Rodič môže potvrdiť alebo odmietnuť účasť iba za svoje nominované dieťa.</p>}
    <div className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white"><ul className="divide-y divide-slate-100">{rows.map((player) => { const attendance = player.attendance_status ?? "unmarked"; return <li className={`p-5 ${player.is_nominated ? "" : "bg-slate-50/70"}`} key={player.player_id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-extrabold text-ink">{player.player_name}</p>{player.decline_reason && <p className="mt-1 text-sm text-slate-600">Dôvod: {player.decline_reason}</p>}</div><div className="flex flex-wrap justify-end gap-2"><span className={player.is_nominated ? "rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-800" : "rounded-full bg-slate-200 px-3 py-1 text-xs font-bold text-slate-600"}>{player.is_nominated ? "Nominovaný" : "Nenominovaný"}</span>{player.is_nominated && player.response && <span className={`rounded-full px-3 py-1 text-xs font-bold ${responseClass[player.response]}`}>Plán: {responseNames[player.response]}</span>}{event.event_type === "training" && player.is_nominated && <span className={`rounded-full px-3 py-1 text-xs font-bold ${attendanceClass[attendance]}`}>{attendanceNames[attendance]}</span>}</div></div>
      {player.can_respond && event.nomination_status === "open" && <div className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-[auto_1fr]"><form action={respondToNomination}><input name="nominationId" type="hidden" value={nominationId}/><input name="teamId" type="hidden" value={event.team_id}/><input name="playerId" type="hidden" value={player.player_id}/><input name="response" type="hidden" value="accepted"/><button className="h-full rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white" type="submit">Zúčastní sa</button></form><form action={respondToNomination} className="flex flex-col gap-3 sm:flex-row sm:items-end"><input name="nominationId" type="hidden" value={nominationId}/><input name="teamId" type="hidden" value={event.team_id}/><input name="playerId" type="hidden" value={player.player_id}/><input name="response" type="hidden" value="declined"/><label className="flex-1 text-xs font-bold text-slate-600">Dôvod neprítomnosti<input className="input mt-1" maxLength={500} minLength={2} name="reason" placeholder="Napíšte dôvod" required/></label><button className="rounded-xl border border-red-200 bg-white px-4 py-2.5 text-sm font-bold text-red-700" type="submit">Nezúčastní sa</button></form></div>}
      {player.can_manage && player.is_nominated && event.event_type === "training" && <div className="mt-3 flex flex-wrap items-center gap-2"><span className="mr-1 text-xs font-bold uppercase tracking-wide text-slate-500">Dochádzka trénera:</span>{([['present', 'Bol'], ['absent', 'Chýbal'], ['unmarked', 'Zrušiť záznam']] as const).map(([status, label]) => <form action={recordTrainingAttendance} key={status}><input name="nominationId" type="hidden" value={nominationId}/><input name="teamId" type="hidden" value={event.team_id}/><input name="playerId" type="hidden" value={player.player_id}/><input name="attendanceStatus" type="hidden" value={status}/><button className={status === "present" ? "rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white" : status === "absent" ? "rounded-lg bg-red-600 px-3 py-2 text-xs font-bold text-white" : "rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600"} type="submit">{label}</button></form>)}</div>}
    </li>})}</ul></div>
  </section>;
}
