"use client";
import { useMemo, useState } from "react";
import type { Club } from "@/types/club";
import { CloseIcon, SearchIcon } from "@/components/icons";

export function ClubPicker({ clubs, selected, onChange }: { clubs: Club[]; selected: string[]; onChange: (ids: string[]) => void }) {
  const [query, setQuery] = useState(""); const [custom, setCustom] = useState(""); const [customTeams, setCustomTeams] = useState<string[]>([]);
  const matches = useMemo(() => clubs.filter((club) => club.name.toLocaleLowerCase("sk").includes(query.toLocaleLowerCase("sk")) && !selected.includes(club.id)).slice(0, 7), [clubs, query, selected]);
  const selectedClubs = selected.map((id) => clubs.find((club) => club.id === id)).filter((club): club is Club => Boolean(club));
  const addCustom = () => { const name = custom.trim(); if (name && !customTeams.includes(name)) { setCustomTeams([...customTeams, name]); setCustom(""); } };
  return <div><div className="flex items-center justify-between"><div><p className="eyebrow">05</p><h2 className="mt-2 text-xl font-extrabold">Prihlásené alebo pozvané tímy</h2><p className="mt-2 text-sm text-slate-500">Vyberte kluby zo zoznamu alebo pridajte vlastný tím.</p></div><span className="rounded-full bg-arena-50 px-3 py-1.5 text-sm font-bold text-arena-700">{selected.length + customTeams.length} vybraných</span></div>
    <div className="relative mt-6"><SearchIcon className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input className="field pl-12" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Vyhľadať klub podľa názvu"/></div>
    {query && <div className="mt-2 overflow-hidden rounded-2xl border bg-white shadow-lg">{matches.length ? matches.map((club) => <button type="button" key={club.id} className="flex w-full items-center gap-3 border-b px-4 py-3 text-left last:border-0 hover:bg-slate-50" onClick={() => { onChange([...selected, club.id]); setQuery(""); }}><ClubMark club={club}/><span><span className="block text-sm font-bold">{club.name}</span><span className="text-xs text-slate-400">{club.city}</span></span><span className="ml-auto text-sm font-bold text-arena-700">+ Pridať</span></button>) : <p className="p-4 text-sm text-slate-500">Žiadny klub sa nenašiel.</p>}</div>}
    {(selectedClubs.length > 0 || customTeams.length > 0) && <div className="mt-5 grid gap-3 sm:grid-cols-2">{selectedClubs.map((club) => <div key={club.id} className="flex items-center gap-3 rounded-2xl border bg-slate-50 p-3"><ClubMark club={club}/><span className="min-w-0 flex-1 truncate text-sm font-bold">{club.name}</span><button type="button" className="text-slate-400 hover:text-red-600" aria-label={`Odstrániť ${club.name}`} onClick={() => onChange(selected.filter((id) => id !== club.id))}><CloseIcon className="h-4 w-4"/></button><input type="hidden" name="clubs" value={club.name}/></div>)}{customTeams.map((name) => <div key={name} className="flex items-center gap-3 rounded-2xl border bg-slate-50 p-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-200 text-xs font-bold">VL</span><span className="min-w-0 flex-1 truncate text-sm font-bold">{name}</span><button type="button" className="text-slate-400 hover:text-red-600" aria-label={`Odstrániť ${name}`} onClick={() => setCustomTeams(customTeams.filter((item) => item !== name))}><CloseIcon className="h-4 w-4"/></button><input type="hidden" name="clubs" value={name}/></div>)}</div>}
    <div className="mt-5 flex gap-3"><input className="field" value={custom} onChange={(e) => setCustom(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addCustom(); } }} placeholder="Vlastný tím mimo zoznam"/><button type="button" className="btn-secondary shrink-0" onClick={addCustom}>Pridať</button></div>
  </div>;
}
function ClubMark({ club }: { club: Club }) { return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-ink text-[10px] font-black text-white">{club.logoPlaceholder}</span>; }
