"use client";
import { FormEvent, useState } from "react";
import { CheckIcon } from "@/components/icons";
import { ClubPicker } from "@/components/club-picker";
import { footballClubs } from "@/data/clubs";

export function CreateTournamentForm() {
  const [summary, setSummary] = useState<Record<string, string | string[]> | null>(null); const [selected, setSelected] = useState<string[]>([]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const fd = new FormData(event.currentTarget); const result: Record<string, string | string[]> = {}; fd.forEach((value, key) => { if (key === "clubs") result[key] = [...(Array.isArray(result[key]) ? result[key] as string[] : result[key] ? [result[key] as string] : []), String(value)]; else result[key] = String(value); }); setSummary(result); window.scrollTo({ top: 0, behavior: "smooth" }); }
  if (summary) return <section className="rounded-3xl border bg-white p-8 shadow-card"><span className="grid h-16 w-16 place-items-center rounded-2xl bg-arena-50 text-arena-600"><CheckIcon className="h-8 w-8"/></span><p className="eyebrow mt-7">Turnaj vytvorený</p><h2 className="mt-3 text-3xl font-black">{summary.name}</h2><p className="mt-3 text-slate-600">Rekapitulácia turnaja. V prototype sa údaje neukladajú.</p><dl className="mt-8 grid gap-5 border-y py-8 sm:grid-cols-2">{Object.entries(summary).map(([key, value]) => <div key={key}><dt className="text-xs font-bold uppercase text-slate-400">{labelMap[key] ?? key}</dt><dd className="mt-1 font-semibold">{Array.isArray(value) ? value.join(", ") : value}{key === "fee" ? " €" : key === "duration" ? " min" : ""}</dd></div>)}</dl><div className="mt-8 flex gap-3"><button className="btn-primary" onClick={() => setSummary(null)}>Vytvoriť ďalší</button><a className="btn-secondary" href="/">Katalóg</a></div></section>;
  return <form onSubmit={submit} className="rounded-3xl border bg-white p-6 shadow-card sm:p-10"><Section n="01" title="Základné informácie"><div className="sm:col-span-2"><Field label="Názov turnaja" name="name" placeholder="Napr. Summer Cup 2027"/></div><Select label="Šport" name="sport" options={["Futbal","Hokej","Florbal","Tenis","Basketbal"]}/><Field label="Veková kategória" name="category" placeholder="Napr. U11"/><Field label="Dátum" name="date" type="date"/><Field label="Miesto" name="place" placeholder="Mesto a športový areál"/></Section><Section n="02" title="Formát turnaja"><Field label="Počet tímov" name="teams" type="number"/><Field label="Počet ihrísk alebo plôch" name="fields" type="number"/><Field label="Dĺžka zápasu (min)" name="duration" type="number"/><Field label="Štartovné (€)" name="fee" type="number"/></Section><ChoiceSection/><div className="mt-9 border-t pt-9"><ClubPicker clubs={footballClubs} selected={selected} onChange={setSelected}/></div><div className="mt-10 flex justify-end border-t pt-8"><button className="btn-primary w-full justify-center sm:w-auto">Vytvoriť turnaj</button></div></form>;
}
const labelMap: Record<string,string> = { name:"Názov",sport:"Šport",category:"Kategória",date:"Dátum",place:"Miesto",teams:"Počet tímov",fields:"Hracie plochy",duration:"Dĺžka zápasu",fee:"Štartovné",type:"Typ",visibility:"Viditeľnosť tímov",clubs:"Vybrané tímy" };
function Section({ n,title,children }:{n:string;title:string;children:React.ReactNode}) { return <fieldset className="mb-9 grid gap-5 border-b pb-9 sm:grid-cols-2"><legend className="mb-6 flex gap-3 text-xl font-extrabold"><span className="text-xs text-arena-600">{n}</span>{title}</legend>{children}</fieldset>; }
function Field({label,name,type="text",placeholder}:{label:string;name:string;type?:string;placeholder?:string}) { return <label><span className="label">{label} *</span><input className="field" name={name} type={type} placeholder={placeholder} min={type === "number" ? 0 : undefined} required/></label>; }
function Select({label,name,options}:{label:string;name:string;options:string[]}) { return <label><span className="label">{label} *</span><select className="field" name={name}>{options.map(x=><option key={x}>{x}</option>)}</select></label>; }
function ChoiceSection() { return <><fieldset className="border-b pb-9"><legend className="mb-6 flex gap-3 text-xl font-extrabold"><span className="text-xs text-arena-600">03</span>Typ turnaja</legend><div className="grid gap-3">{[["Verejný","Turnaj sa zobrazí v katalógu a tímy môžu posielať prihlášky."],["Pozvánkový","Turnaj je dostupný iba cez pozvánku."],["Kombinovaný","Pozvánky aj verejné prihlášky."]].map(([v,d],i)=><Radio key={v} name="type" value={v} desc={d} checked={i===0}/>)}</div></fieldset><fieldset className="mt-9 border-b pb-9"><legend className="mb-6 flex gap-3 text-xl font-extrabold"><span className="text-xs text-arena-600">04</span>Zobrazenie prihlásených tímov</legend><div className="grid gap-3 sm:grid-cols-3">{["Zobrazovať všetkým","Iba prijatým tímom","Nezobrazovať"].map((v,i)=><Radio key={v} name="visibility" value={v} checked={i===0}/>)}</div></fieldset></>; }
function Radio({name,value,desc,checked}:{name:string;value:string;desc?:string;checked?:boolean}) { return <label className="flex cursor-pointer gap-3 rounded-2xl border p-4 hover:border-arena-500 has-[:checked]:border-arena-500 has-[:checked]:bg-arena-50"><input className="mt-1 accent-arena-600" type="radio" name={name} value={value} defaultChecked={checked}/><span><b className="block text-sm">{value}</b>{desc&&<span className="text-xs text-slate-500">{desc}</span>}</span></label>; }
