"use client";
import { useRef, useState } from "react";
import { ClubPicker } from "@/components/club-picker";
import type { Club } from "@/types/club";
import { createTournament } from "@/app/vytvorit-turnaj/actions";
import { updateTournament } from "@/app/turnaje/[slug]/upravit/actions";
import type { TournamentEditSource, TournamentRepeatSource } from "@/lib/tournaments";
import { createScheduleSummary, type GameSystem } from "@/lib/tournament-schedule";

export function CreateTournamentForm({ clubs, repeatSource, editSource }: { clubs: Club[]; repeatSource?: TournamentRepeatSource | null; editSource?: TournamentEditSource | null }) {
  const source = editSource ?? repeatSource;
  const confirmReset = useRef<HTMLInputElement>(null);
  const [selected, setSelected] = useState<string[]>(source?.clubIds ?? []);
  const [teams, setTeams] = useState(source?.capacity ?? 8);
  const [fields, setFields] = useState(source?.playingFields ?? 2);
  const [duration, setDuration] = useState(source?.matchDuration ?? 12);
  const [startTime, setStartTime] = useState(source?.startTime ?? "09:00");
  const [lunchBreak, setLunchBreak] = useState(source?.lunchBreak ?? false);
  const [lunchStart, setLunchStart] = useState(source?.lunchStart ?? "12:00");
  const [lunchDuration, setLunchDuration] = useState(source?.lunchDuration ?? 45);
  const [gameSystem, setGameSystem] = useState<GameSystem>(source?.gameSystem ?? "groups_playoff");
  const [qualifiers, setQualifiers] = useState(source?.qualifiersPerGroup ?? 2);
  const [thirdPlace, setThirdPlace] = useState(source?.thirdPlaceMatch ?? true);
  const schedule = createScheduleSummary({ teamCount: teams, fieldCount: fields, matchMinutes: duration, startTime, lunchBreak, lunchStart, lunchDuration, gameSystem, qualifiersPerGroup: qualifiers, thirdPlaceMatch: thirdPlace });
  return <form action={editSource ? updateTournament : createTournament} onSubmit={(event) => { if (editSource?.hasResults && !window.confirm("Ak ste zmenili formát turnaja, vytvorí sa nový rozpis a doterajšie výsledky sa vymažú. Chcete pokračovať?")) event.preventDefault(); else if (confirmReset.current) confirmReset.current.value = "yes"; }} className="rounded-3xl border bg-white p-6 shadow-card sm:p-10">
    {editSource && <><input type="hidden" name="slug" value={editSource.slug}/><input ref={confirmReset} type="hidden" name="confirmReset" value="no"/><div className="mb-8 rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4"><p className="font-bold text-amber-900">Upravujete existujúci turnaj</p><p className="mt-1 text-sm text-amber-800">Zmena počtu tímov, herného systému, ihrísk alebo časov vytvorí nový rozpis. Bežné údaje výsledky neovplyvnia.</p></div></>}
    {repeatSource && <div className="mb-8 rounded-2xl border border-arena-200 bg-arena-50 px-5 py-4"><p className="font-bold text-arena-800">Vytvárate nový turnaj podľa „{repeatSource.name}“</p><p className="mt-1 text-sm text-arena-700">Vyberte nový dátum a skontrolujte predvyplnené údaje. Prihlášky, nominácie ani výsledky sa nekopírujú.</p></div>}
    <Section n="01" title="Základné informácie"><div className="sm:col-span-2"><Field label="Názov turnaja" name="name" placeholder="Napr. Summer Cup 2027" defaultValue={source?.name}/></div><Select label="Šport" name="sport" options={["Futbal","Hokej","Florbal","Tenis","Basketbal"]} defaultValue={source?.sport}/><Field label="Veková kategória" name="category" placeholder="Napr. U11" defaultValue={source?.category}/><Field label={editSource ? "Dátum" : "Nový dátum"} name="date" type="date" defaultValue={editSource?.eventDate}/><Field label="Miesto" name="place" placeholder="Mesto a športový areál" defaultValue={source?.place}/></Section>
    <Section n="02" title="Formát a čas"><Field label="Počet tímov" name="teams" type="number" min={2} defaultValue={teams} onNumberChange={setTeams}/><Field label="Počet ihrísk alebo plôch" name="fields" type="number" min={1} defaultValue={fields} onNumberChange={setFields}/><Field label="Dĺžka zápasu (min)" name="duration" type="number" min={1} defaultValue={duration} onNumberChange={setDuration}/><Field label="Začiatok prvého zápasu" name="startTime" type="time" defaultValue={startTime} onChange={setStartTime}/><label className="sm:col-span-2 flex cursor-pointer items-start gap-3 rounded-2xl border bg-slate-50 p-4"><input className="mt-1 accent-arena-600" type="checkbox" name="lunchBreak" checked={lunchBreak} onChange={(event) => setLunchBreak(event.target.checked)}/><span><b className="block text-sm">Zahrnúť obednú prestávku</b><span className="text-xs text-slate-500">Prestávku aplikácia vloží medzi celé zápasy.</span></span></label>{lunchBreak && <><Field label="Začiatok obednej prestávky" name="lunchStart" type="time" defaultValue={lunchStart} onChange={setLunchStart}/><Field label="Dĺžka obednej prestávky (min)" name="lunchDuration" type="number" min={15} defaultValue={lunchDuration} onNumberChange={setLunchDuration}/></>}<Field label="Štartovné (€)" name="fee" type="number" min={0} defaultValue={source?.fee}/><SchedulePreview schedule={schedule}/></Section>
    <GameSystemSection gameSystem={gameSystem} setGameSystem={setGameSystem} qualifiers={qualifiers} setQualifiers={setQualifiers} thirdPlace={thirdPlace} setThirdPlace={setThirdPlace}/><ChoiceSection tournamentType={source?.tournamentType} teamVisibility={source?.teamVisibility}/><div className="mt-9 border-t pt-9"><ClubPicker clubs={clubs} selected={selected} onChange={setSelected} initialCustomTeams={source?.customTeams}/></div><div className="mt-10 flex justify-end border-t pt-8"><button className="btn-primary w-full justify-center sm:w-auto" type="submit">{editSource ? "Uložiť zmeny" : "Uložiť a zverejniť turnaj"}</button></div>
  </form>;
}
function Section({ n,title,children }:{n:string;title:string;children:React.ReactNode}) { return <fieldset className="mb-9 grid gap-5 border-b pb-9 sm:grid-cols-2"><legend className="mb-6 flex gap-3 text-xl font-extrabold"><span className="text-xs text-arena-600">{n}</span>{title}</legend>{children}</fieldset>; }
function Field({label,name,type="text",placeholder,min,defaultValue,onChange,onNumberChange}:{label:string;name:string;type?:string;placeholder?:string;min?:number;defaultValue?:string|number;onChange?:(value:string)=>void;onNumberChange?:(value:number)=>void}) { return <label><span className="label">{label} *</span><input className="field" name={name} type={type} placeholder={placeholder} min={min} defaultValue={defaultValue} onChange={(event) => { onChange?.(event.target.value); onNumberChange?.(Number(event.target.value)); }} required/></label>; }
function Select({label,name,options,defaultValue}:{label:string;name:string;options:string[];defaultValue?:string}) { return <label><span className="label">{label} *</span><select className="field" name={name} defaultValue={defaultValue}>{options.map(x=><option key={x}>{x}</option>)}</select></label>; }
function GameSystemSection({gameSystem,setGameSystem,qualifiers,setQualifiers,thirdPlace,setThirdPlace}:{gameSystem:GameSystem;setGameSystem:(value:GameSystem)=>void;qualifiers:number;setQualifiers:(value:number)=>void;thirdPlace:boolean;setThirdPlace:(value:boolean)=>void}) { const options:[GameSystem,string,string][] = [["groups_playoff","Skupiny + play-off","Každý s každým v skupine, potom vyraďovacia časť."],["round_robin","Každý s každým","Jedna spoločná tabuľka bez vyraďovacej časti."],["groups_placement","Skupiny + umiestnenie","Skupiny a následne zápasy o konečné umiestnenie."]]; return <fieldset className="mb-9 border-b pb-9"><legend className="mb-6 flex gap-3 text-xl font-extrabold"><span className="text-xs text-arena-600">03</span>Systém hry</legend><div className="grid gap-3">{options.map(([value,label,desc])=><label key={value} className="flex cursor-pointer gap-3 rounded-2xl border p-4 hover:border-arena-500 has-[:checked]:border-arena-500 has-[:checked]:bg-arena-50"><input className="mt-1 accent-arena-600" type="radio" name="gameSystem" value={value} checked={gameSystem===value} onChange={()=>setGameSystem(value)}/><span><b className="block text-sm">{label}</b><span className="text-xs text-slate-500">{desc}</span></span></label>)}</div>{gameSystem === "groups_playoff" && <div className="mt-5 grid gap-4 rounded-2xl bg-slate-50 p-4 sm:grid-cols-2"><label><span className="label">Postupujúci z každej skupiny</span><select className="field" name="qualifiersPerGroup" value={qualifiers} onChange={(event)=>setQualifiers(Number(event.target.value))}><option value={1}>1 tím</option><option value={2}>2 tímy</option></select></label><label className="flex cursor-pointer items-center gap-3 sm:pt-7"><input className="accent-arena-600" type="checkbox" name="thirdPlaceMatch" checked={thirdPlace} onChange={(event)=>setThirdPlace(event.target.checked)}/><span className="text-sm font-bold">Hrať zápas o 3. miesto</span></label></div>}</fieldset>; }
function ChoiceSection({ tournamentType = "Verejný", teamVisibility = "Zobrazovať všetkým" }:{tournamentType?:string;teamVisibility?:string}) { return <><fieldset className="border-b pb-9"><legend className="mb-6 flex gap-3 text-xl font-extrabold"><span className="text-xs text-arena-600">04</span>Typ turnaja</legend><div className="grid gap-3">{[["Verejný","Turnaj sa zobrazí v katalógu a tímy môžu posielať prihlášky."],["Pozvánkový","Turnaj je dostupný iba cez pozvánku."],["Kombinovaný","Pozvánky aj verejné prihlášky."]].map(([v,d])=><Radio key={v} name="type" value={v} desc={d} checked={v===tournamentType}/>)}</div></fieldset><fieldset className="mt-9 border-b pb-9"><legend className="mb-6 flex gap-3 text-xl font-extrabold"><span className="text-xs text-arena-600">05</span>Zobrazenie prihlásených tímov</legend><div className="grid gap-3 sm:grid-cols-3">{["Zobrazovať všetkým","Iba prijatým tímom","Nezobrazovať"].map((v)=><Radio key={v} name="visibility" value={v} checked={v===teamVisibility}/>)}</div></fieldset></>; }
function Radio({name,value,desc,checked}:{name:string;value:string;desc?:string;checked?:boolean}) { return <label className="flex cursor-pointer gap-3 rounded-2xl border p-4 hover:border-arena-500 has-[:checked]:border-arena-500 has-[:checked]:bg-arena-50"><input className="mt-1 accent-arena-600" type="radio" name={name} value={value} defaultChecked={checked}/><span><b className="block text-sm">{value}</b>{desc&&<span className="text-xs text-slate-500">{desc}</span>}</span></label>; }
function SchedulePreview({ schedule }: { schedule: ReturnType<typeof createScheduleSummary> }) { if (!schedule) return null; return <div className="sm:col-span-2 rounded-2xl border border-arena-200 bg-arena-50 p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-arena-700">Odporúčanie Tournio</p><p className="mt-2 font-extrabold">{schedule.matchCount} zápasov · predpokladaný koniec {schedule.finishTime}</p><p className="mt-1 text-xs text-arena-700">Skupinová časť {schedule.groupMatchCount}{schedule.finalStageMatchCount > 0 && ` · záverečná časť ${schedule.finalStageMatchCount}`}</p><p className="mt-2 text-sm leading-6 text-arena-800">Zápas {durationText(schedule.slotMinutes - schedule.turnoverMinutes)}, časový blok {durationText(schedule.slotMinutes)} a prestávka {durationText(schedule.turnoverMinutes)}. Navrhujeme {schedule.groupSizes.length === 1 ? "1 tabuľku" : `${schedule.groupSizes.length} skupiny`} ({schedule.groupSizes.join(" + ")} tímov). Každý tím má medzi zápasmi aspoň jeden celý blok voľna.</p>{schedule.restSlotCount > 0 && <p className="mt-2 text-xs text-arena-700">Pre spravodlivý odpočinok obsahuje návrh aj {schedule.restSlotCount} {schedule.restSlotCount === 1 ? "voľný blok" : "voľné bloky"}.</p>}</div>; }
function durationText(value:number) { return `${value} min`; }
