"use client";
import { FormEvent, useEffect, useState } from "react";
import { CheckIcon, CloseIcon } from "@/components/icons";

export function SignupModal({ disabled = false }: { disabled?: boolean }) {
  const [open, setOpen] = useState(false); const [sent, setSent] = useState(false);
  useEffect(() => { if (!open) return; const handler = (event: KeyboardEvent) => event.key === "Escape" && setOpen(false); document.addEventListener("keydown", handler); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", handler); document.body.style.overflow = ""; }; }, [open]);
  function submit(event: FormEvent) { event.preventDefault(); setSent(true); }
  return <><button className="btn-primary w-full justify-center sm:w-auto" disabled={disabled} onClick={() => { setOpen(true); setSent(false); }}>{disabled ? "Kapacita je naplnená" : "Prihlásiť tím"}</button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/50 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={(e) => e.target === e.currentTarget && setOpen(false)}><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex justify-between"><div><p className="eyebrow">Prihláška</p><h2 id="modal-title" className="mt-2 text-2xl font-extrabold">Prihlásiť tím</h2></div><button className="icon-button" onClick={() => setOpen(false)} aria-label="Zavrieť"><CloseIcon/></button></div>{sent ? <div className="py-12 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-arena-50 text-arena-600"><CheckIcon className="h-8 w-8"/></span><h3 className="mt-5 text-xl font-bold">Ďakujeme za prihlášku</h3><p className="mx-auto mt-2 max-w-sm text-slate-600">Prihláška bola odoslaná organizátorovi na schválenie.</p><button className="btn-primary mt-7" onClick={() => setOpen(false)}>Hotovo</button></div> : <form className="mt-7 space-y-5" onSubmit={submit}><FormField label="Názov tímu" name="team"/><FormField label="Meno kontaktnej osoby" name="contact"/><div className="grid gap-5 sm:grid-cols-2"><FormField label="E-mail" name="email" type="email"/><FormField label="Telefón" name="phone" type="tel"/></div><label className="block"><span className="label">Poznámka</span><textarea className="field min-h-28" name="note"/></label><button className="btn-primary w-full justify-center" type="submit">Odoslať prihlášku</button></form>}</div></div>}</>;
}
function FormField({ label, name, type = "text" }: { label: string; name: string; type?: string }) { return <label className="block"><span className="label">{label}</span><input className="field" name={name} type={type} required/></label>; }
