"use client";
import { useMemo, useState } from "react";
import type { Tournament } from "@/types/tournament";
import { SearchIcon } from "@/components/icons";
import { TournamentCard } from "@/components/tournament-card";

export function TournamentCatalog({ tournaments, sports }: { tournaments: Tournament[]; sports: string[] }) {
  const [query, setQuery] = useState(""); const [sport, setSport] = useState("Všetky športy"); const [category, setCategory] = useState("Všetky kategórie"); const [country, setCountry] = useState("Všetky krajiny"); const [date, setDate] = useState("");
  const filtered = useMemo(() => tournaments.filter((item) => { const q = query.trim().toLocaleLowerCase("sk"); return (!q || item.name.toLocaleLowerCase("sk").includes(q) || item.city.toLocaleLowerCase("sk").includes(q)) && (sport === "Všetky športy" || item.sport === sport) && (category === "Všetky kategórie" || item.category === category) && (country === "Všetky krajiny" || item.country === country) && (!date || item.date >= date); }), [tournaments, query, sport, category, country, date]);
  const reset = () => { setQuery(""); setSport("Všetky športy"); setCategory("Všetky kategórie"); setCountry("Všetky krajiny"); setDate(""); };
  return <section id="turnaje" className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="-mt-12 rounded-3xl border bg-white p-4 shadow-card md:p-5"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-[1.7fr_repeat(4,1fr)]"><label className="relative"><span className="sr-only">Hľadať</span><SearchIcon className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input className="field pl-12" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Názov turnaja alebo mesto" /></label><Filter value={sport} set={setSport} options={sports}/><Filter value={category} set={setCategory} options={["Všetky kategórie","U10","U11","U12","U13","U14"]}/><Filter value={country} set={setCountry} options={["Všetky krajiny","Slovensko","Česko"]}/><label><span className="sr-only">Dátum od</span><input type="date" className="field" value={date} onChange={(e) => setDate(e.target.value)} /></label></div></div><div className="mb-7 mt-14 flex items-end justify-between"><div><p className="eyebrow">Aktuálna ponuka</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight">Turnaje pre mladé talenty</h2></div><p className="hidden text-sm text-slate-500 sm:block">{filtered.length} turnajov</p></div>{filtered.length ? <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => <TournamentCard key={item.slug} tournament={item}/>)}</div> : <div className="rounded-3xl border border-dashed bg-white py-16 text-center"><p className="text-lg font-bold">Nenašli sme žiadny turnaj</p><p className="mt-2 text-slate-500">Skúste upraviť vyhľadávanie alebo filtre.</p><button className="btn-secondary mt-5" onClick={reset}>Vymazať filtre</button></div>}</section>;
}
function Filter({ value, set, options }: { value: string; set: (value: string) => void; options: string[] }) { return <label><span className="sr-only">Filter</span><select className="field" value={value} onChange={(e) => set(e.target.value)}>{options.map((x) => <option key={x}>{x}</option>)}</select></label>; }
