-- Curated Slovak football club directory, cross-checked against the public
-- Sportnet competition directory and current national/regional league lists.
with imported (id, name, short_name, city, mark) as (
  values
    ('msk-zilina', 'MŠK Žilina', 'MŠK Žilina', 'Žilina', 'MŠK'),
    ('zeleziarne-podbrezova', 'FK Železiarne Podbrezová', 'Podbrezová', 'Podbrezová', 'ŽP'),
    ('fc-kosice', 'FC KOŠICE', 'FC Košice', 'Košice', 'FCK'),
    ('zemplin-michalovce', 'MFK Zemplín Michalovce', 'Michalovce', 'Michalovce', 'ZEM'),
    ('ruzomberok', 'MFK Ružomberok', 'Ružomberok', 'Ružomberok', 'RUŽ'),
    ('dukla-banska-bystrica', 'MFK Dukla Banská Bystrica', 'Dukla', 'Banská Bystrica', 'DDB'),
    ('tatran-presov', 'FC TATRAN Prešov', 'Tatran Prešov', 'Prešov', 'TAT'),
    ('pohronie', 'FK POHRONIE Žiar nad Hronom Dolná Ždaňa', 'Pohronie', 'Žiar nad Hronom', 'POH'),
    ('tatran-liptovsky-mikulas', 'MFK Tatran Liptovský Mikuláš', 'Tatran LM', 'Liptovský Mikuláš', 'TLM'),
    ('slovan-galanta', 'FC Slovan Galanta', 'Slovan Galanta', 'Galanta', 'GAL'),
    ('dynamo-malzenice', 'OFK Dynamo Malženice', 'Dynamo Malženice', 'Malženice', 'DYM'),
    ('mfk-zvolen', 'MFK Zvolen', 'MFK Zvolen', 'Zvolen', 'ZVO'),
    ('mfk-bytca', 'MFK Bytča', 'MFK Bytča', 'Bytča', 'BYT'),
    ('banik-lehota', 'FK Baník Lehota pod Vtáčnikom', 'Baník Lehota', 'Lehota pod Vtáčnikom', 'BLV'),
    ('slavia-tu-kosice', 'Slávia TU Košice', 'Slávia TU', 'Košice', 'STU'),
    ('redfox-stara-lubovna', 'Redfox FC Stará Ľubovňa', 'Stará Ľubovňa', 'Stará Ľubovňa', 'SL'),
    ('fk-belusa', 'FK Beluša', 'Beluša', 'Beluša', 'BEL'),
    ('slovan-duslo-sala', 'FK Slovan Duslo Šaľa', 'Šaľa', 'Šaľa', 'ŠAĽ'),
    ('fkm-nove-zamky', 'FKM Nové Zámky', 'Nové Zámky', 'Nové Zámky', 'NZ'),
    ('velke-ludince', 'TJ Družstevník Veľké Ludince', 'Veľké Ludince', 'Veľké Ludince', 'VL'),
    ('spartak-myjava', 'Spartak Myjava', 'Myjava', 'Myjava', 'MYJ'),
    ('ok-castkovce', 'OK Častkovce', 'Častkovce', 'Častkovce', 'ČAS'),
    ('podkonice', 'FK Podkonice', 'Podkonice', 'Podkonice', 'POD'),
    ('rsc-hamsik-academy', 'RSC Hamsik Academy', 'Hamsik Academy', 'Banská Bystrica', 'RSC'),
    ('fomat-martin', 'MŠK Fomat Martin', 'Fomat Martin', 'Martin', 'FOM'),
    ('banova', 'TJ Jednota Bánová', 'Bánová', 'Žilina', 'BÁN'),
    ('rimavska-sobota', 'MŠK Rimavská Sobota', 'Rimavská Sobota', 'Rimavská Sobota', 'RS'),
    ('msk-namestovo', 'MŠK Námestovo', 'Námestovo', 'Námestovo', 'NÁM'),
    ('dolny-kubin', 'MFK Dolný Kubín', 'Dolný Kubín', 'Dolný Kubín', 'DK'),
    ('tj-banik-kalinovo', 'TJ Baník Kalinovo', 'Kalinovo', 'Kalinovo', 'KAL'),
    ('ftc-filakovo', 'FTC Fiľakovo', 'Fiľakovo', 'Fiľakovo', 'FTC'),
    ('novohrad-lucenec', 'MŠK Novohrad Lučenec', 'Novohrad Lučenec', 'Lučenec', 'NLC'),
    ('oravske-vesele', 'TJ Tatran Oravské Veselé', 'Oravské Veselé', 'Oravské Veselé', 'OV'),
    ('mfk-snina', 'MFK Snina', 'MFK Snina', 'Snina', 'SNI'),
    ('vranov-nad-toplou', 'MFK Vranov nad Topľou', 'Vranov', 'Vranov nad Topľou', 'VNT'),
    ('spisska-nova-ves', 'FK Spišská Nová Ves', 'Spišská Nová Ves', 'Spišská Nová Ves', 'SNV'),
    ('tesla-stropkov', 'MŠK Tesla Stropkov', 'Tesla Stropkov', 'Stropkov', 'TES'),
    ('fk-poprad', 'FK Poprad', 'FK Poprad', 'Poprad', 'POP'),
    ('odeva-lipany', 'ŠK Odeva Lipany', 'Odeva Lipany', 'Lipany', 'ODE'),
    ('lokomotiva-kosice', 'FC Lokomotíva Košice', 'Lokomotíva', 'Košice', 'LKO'),
    ('spisske-podhradie', 'MŠK Spišské Podhradie', 'Spišské Podhradie', 'Spišské Podhradie', 'SP'),
    ('fk-medzev', 'FK Medzev', 'Medzev', 'Medzev', 'MED'),
    ('mfk-kezmarok', '1. MFK Kežmarok', 'MFK Kežmarok', 'Kežmarok', 'KEŽ'),
    ('msk-sabinov', 'MŠK Slovan Sabinov', 'Sabinov', 'Sabinov', 'SAB'),
    ('raslavice', 'OFK SIM Raslavice', 'Raslavice', 'Raslavice', 'RAS'),
    ('fc-rohoznik', 'FC Rohožník', 'Rohožník', 'Rohožník', 'ROH'),
    ('slovan-modra', 'FC Slovan Modra', 'Slovan Modra', 'Modra', 'MOD'),
    ('lokomotiva-devinska', 'FK Lokomotíva Devínska Nová Ves', 'Lokomotíva DNV', 'Bratislava', 'DNV'),
    ('slovan-ivanka', 'FK Slovan Ivanka pri Dunaji', 'Slovan Ivanka', 'Ivanka pri Dunaji', 'IVA'),
    ('kralova-pri-senci', 'MŠK Kráľová pri Senci', 'Kráľová pri Senci', 'Kráľová pri Senci', 'KPS'),
    ('mfk-rusovce', 'MFK Rusovce', 'Rusovce', 'Bratislava', 'RUS'),
    ('nsk-1922', 'NŠK 1922 Bratislava', 'NŠK 1922', 'Bratislava', 'NŠK'),
    ('dunajska-luzna', 'OFK Dunajská Lužná', 'Dunajská Lužná', 'Dunajská Lužná', 'DL'),
    ('psc-pezinok', 'PŠC Pezinok', 'PŠC Pezinok', 'Pezinok', 'PŠC'),
    ('sfc-kalinkovo', 'SFC Kalinkovo', 'Kalinkovo', 'Kalinkovo', 'SFC'),
    ('sk-bernolakovo', 'ŠK Bernolákovo', 'Bernolákovo', 'Bernolákovo', 'ŠKB'),
    ('sk-nova-dedinka', 'ŠK Nová Dedinka', 'Nová Dedinka', 'Nová Dedinka', 'ND'),
    ('sk-tomasov', 'ŠK Tomášov', 'Tomášov', 'Tomášov', 'TOM'),
    ('zahoran-jakubov', 'TJ Záhoran Jakubov', 'Záhoran Jakubov', 'Jakubov', 'ZAH'),
    ('tj-rovinka', 'TJ Rovinka', 'Rovinka', 'Rovinka', 'ROV'),
    ('skf-sered', 'ŠKF Sereď', 'ŠKF Sereď', 'Sereď', 'SER'),
    ('fc-pata', 'FC Pata', 'FC Pata', 'Pata', 'PAT'),
    ('pfk-piestany', 'PFK Piešťany', 'PFK Piešťany', 'Piešťany', 'PFK'),
    ('sk-soporna', 'ŠK Šoporňa', 'Šoporňa', 'Šoporňa', 'ŠOP'),
    ('ofk-trebatice', 'OFK Trebatice', 'Trebatice', 'Trebatice', 'TRE'),
    ('trencianske-stankovce', 'OŠK Trenčianske Stankovce', 'Trenčianske Stankovce', 'Trenčianske Stankovce', 'TS'),
    ('sk-lr-crystal', 'ŠK LR CRYSTAL', 'LR Crystal', 'Lednické Rovne', 'LRC'),
    ('tj-imel', 'TJ Imeľ', 'Imeľ', 'Imeľ', 'IME'),
    ('sk-blava-1928', 'ŠK Blava 1928', 'Blava 1928', 'Jaslovské Bohunice', 'BLV'),
    ('bestrent-horna-krupa', 'FK Bestrent Horná Krupá', 'Horná Krupá', 'Horná Krupá', 'HK'),
    ('nafta-gbely', 'TJ Nafta Gbely', 'Nafta Gbely', 'Gbely', 'NGB'),
    ('slavoj-boleraz', 'TJ Slavoj Boleráz', 'Slavoj Boleráz', 'Boleráz', 'BOL'),
    ('afc-nove-mesto', 'AFC Nové Mesto nad Váhom', 'AFC Nové Mesto', 'Nové Mesto nad Váhom', 'AFC'),
    ('sk-badin', 'ŠK Badín', 'ŠK Badín', 'Badín', 'BAD'),
    ('slavia-staskov', 'FK Slávia Staškov', 'Slávia Staškov', 'Staškov', 'STA'),
    ('spartak-radostka', 'TJ Spartak Radôstka', 'Spartak Radôstka', 'Radôstka', 'RAD'),
    ('banik-stranavy', 'OŠK Baník Stráňavy', 'Baník Stráňavy', 'Stráňavy', 'STR'),
    ('sk-javornik-makov', 'ŠK Javorník Makov', 'Javorník Makov', 'Makov', 'JAV'),
    ('pramen-kovacova', 'ŠK Prameň Kováčová', 'Prameň Kováčová', 'Kováčová', 'KOV'),
    ('osk-rosina', 'OŠK Rosina', 'Rosina', 'Rosina', 'ROS'),
    ('filjo-ladomerska-vieska', 'FK FILJO Ladomerská Vieska', 'FILJO', 'Ladomerská Vieska', 'FIL'),
    ('sokol-medzibrod', 'TJ Sokol Medzibrod', 'Sokol Medzibrod', 'Medzibrod', 'MED'),
    ('sokol-zubrohlava', 'TJ Sokol Zubrohlava', 'Sokol Zubrohlava', 'Zubrohlava', 'ZUB'),
    ('tatran-krasno', 'TJ Tatran Krásno nad Kysucou', 'Tatran Krásno', 'Krásno nad Kysucou', 'KRÁ'),
    ('partizan-osrblie', 'TJ Partizán Osrblie', 'Partizán Osrblie', 'Osrblie', 'OSR'),
    ('partizan-bardejov', 'Partizán Bardejov', 'Partizán Bardejov', 'Bardejov', 'BAR'),
    ('mfk-roznava', 'MFK Rožňava', 'MFK Rožňava', 'Rožňava', 'ROŽ'),
    ('velky-saris', 'FC Pivovar Šariš Veľký Šariš', 'Veľký Šariš', 'Veľký Šariš', 'VŠ'),
    ('fk-cana', 'FK Čaňa', 'FK Čaňa', 'Čaňa', 'ČAŇ'),
    ('fk-gerlachov', 'FK Gerlachov', 'Gerlachov', 'Gerlachov', 'GER'),
    ('fk-kechnec', 'FK Kechnec', 'Kechnec', 'Kechnec', 'KEC'),
    ('sk-zahradne', 'ŠK Záhradné', 'Záhradné', 'Záhradné', 'ZÁH'),
    ('sobrance-sobranecko', 'FK Sobrance-Sobranecko', 'Sobrance', 'Sobrance', 'SOB'),
    ('slovan-kendice', 'FK Slovan Kendice', 'Slovan Kendice', 'Kendice', 'KEN'),
    ('fk-geca-73', 'FK Geča 73', 'Geča 73', 'Geča', 'GEČ'),
    ('spartak-medzilaborce', 'MŠK Spartak Medzilaborce', 'Spartak Medzilaborce', 'Medzilaborce', 'SML'),
    ('sokol-lubotice', 'TJ Sokol Ľubotice', 'Sokol Ľubotice', 'Ľubotice', 'ĽUB'),
    ('pavlovce-nad-uhom', 'OŠK Pavlovce nad Uhom', 'Pavlovce nad Uhom', 'Pavlovce nad Uhom', 'PNU'),
    ('osk-rudnany', 'OŠK Rudňany', 'Rudňany', 'Rudňany', 'RUD')
)
insert into public.clubs (
  id, name, short_name, sport, country, city, logo_placeholder,
  source, source_id, source_url, status
)
select
  imported.id,
  imported.name,
  imported.short_name,
  'football',
  'Slovensko',
  imported.city,
  imported.mark,
  'curated_public_directory',
  imported.id,
  'https://sportnet.sme.sk/futbalnet/k/',
  'active'
from imported
where not exists (
  select 1 from public.clubs existing
  where lower(existing.name) = lower(imported.name)
     or existing.id = imported.id
)
on conflict do nothing;
