import Link from "next/link";
import { notFound } from "next/navigation";
import { CalendarIcon, CheckIcon, PinIcon, TrophyIcon, UsersIcon } from "@/components/icons";
import { SignupModal } from "@/components/signup-modal";
import { tournaments } from "@/data/tournaments";
import { clubsById } from "@/data/clubs";
export function generateStaticParams() { return tournaments.map(({ slug }) => ({ slug })); }
export default async function TournamentDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const tournament = tournaments.find((item) => item.slug === slug); if (!tournament) notFound(); const free = tournament.capacity - tournament.registered; const full = free === 0; const clubs = (tournament.participantClubIds ?? []).map((id) => clubsById.get(id)).filter((club) => club !== undefined); const names = clubs.length ? clubs.map((club) => club.name) : tournament.participants;
  return <><section className="border-b bg-white"><div className="mx-auto max-w-7xl px-5 py-12 lg:px-8 lg:py-16"><Link href="/" className="text-sm font-bold text-slate-500 hover:text-arena-700">← Späť na turnaje</Link><div className="mt-8 flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><div className="flex gap-2"><span className="sport-pill">{tournament.sport}</span><span className="sport-pill bg-slate-100 text-slate-600">{tournament.category}</span></div><h1 className="mt-5 text-4xl font-black tracking-[-0.03em] sm:text-5xl">{tournament.name}</h1><div className="mt-6 flex flex-col gap-3 text-slate-600 sm:flex-row sm:gap-7"><p className="detail-row"><CalendarIcon/>{tournament.displayDate}</p><p className="detail-row"><PinIcon/>{tournament.city}, {tournament.country}</p></div></div><SignupModal disabled={full}/></div></div></section><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 lg:grid-cols-[1fr_360px] lg:px-8"><div className="space-y-8"><Card title="Športový víkend, na ktorý sa nezabúda" eyebrow="O turnaji"><p className="leading-7 text-slate-600">{tournament.description}</p></Card><Card title="Základné pravidlá" eyebrow="Pravidlá"><ul className="grid gap-4 sm:grid-cols-2">{tournament.rules.map((rule) => <li className="flex gap-3 text-sm text-slate-600" key={rule}><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-arena-50 text-arena-600"><CheckIcon className="h-4 w-4"/></span>{rule}</li>)}</ul></Card><Card title={`Prihlásené ${tournament.participantLabel}`} eyebrow="Účastníci"><div className="grid gap-3 sm:grid-cols-2">{names.map((name, i) => <div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4" key={name}><span className="grid h-10 w-10 place-items-center rounded-xl bg-ink text-[10px] font-black text-white">{clubs[i]?.logoPlaceholder ?? i + 1}</span><span className="font-semibold">{name}</span></div>)}</div></Card></div><aside><div className="sticky top-28 rounded-3xl bg-ink p-8 text-white shadow-xl"><p className="text-sm font-bold text-arena-500">Informácie</p><dl className="mt-6 space-y-5"><Info icon={<TrophyIcon/>} term="Organizátor" value={tournament.organizer}/><Info icon={<UsersIcon/>} term="Voľné miesta" value={full ? "Kapacita naplnená" : `${free} ${tournament.participantLabel}`}/><Info icon={<CalendarIcon/>} term="Stav registrácie" value={tournament.status}/></dl><div className="my-7 h-px bg-white/10"/><p className="text-sm text-slate-400">Štartovné</p><p className="mt-1 text-3xl font-black">{tournament.fee} €</p><div className="mt-7"><SignupModal disabled={full}/></div></div></aside></div></>;
}
function Card({ title, eyebrow, children }: { title: string; eyebrow: string; children: React.ReactNode }) { return <section className="rounded-3xl border bg-white p-6 shadow-card sm:p-8"><p className="eyebrow">{eyebrow}</p><h2 className="mb-6 mt-3 text-2xl font-extrabold">{title}</h2>{children}</section>; }
function Info({ icon, term, value }: { icon: React.ReactNode; term: string; value: string }) { return <div className="flex gap-3"><span className="text-arena-500">{icon}</span><div><dt className="text-xs text-slate-400">{term}</dt><dd className="mt-0.5 text-sm font-semibold">{value}</dd></div></div>; }
